name: Deploy to Server
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Server SSH Known Hosts
        run: |
          ssh-keyscan -H -p ${{ secrets.PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}       # IP-адрес сервера
          username: ${{ secrets.USERNAME }}    # Пользователь (например, root)
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Приватный SSH-ключ
          port: ${{ secrets.PORT }}            # Порт (например, 22)
          script: |
            cd /var/www/html/KilMonda          # Путь к проекту (не через secrets!)
            git pull origin main
            sudo systemctl restart nginx